spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdemo_db
    username: postgres
    password: bcarr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

